### PR TITLE
lab6 submission

### PR DESCRIPTION
**Pull request by efano**

### CODE REVIEW

**Review by brucestull — CHANGES_REQUESTED** [review]
[Grocery List](https://github.com/PdxCodeGuild/class_kiwi/blob/main/3%20Django/labs/03%20Grocery%20List)

**Needs Work**
1. "The user should be able to mark an item complete/incomplete"

The app is awesome! Great graphics! Good execution. The Checkmark works great for completing an item but I was unable to move an item back to "Need". Perfect execution otherwise.

**Review by brucestull — CHANGES_REQUESTED** [review]
There is a merge conflict but I'm not sure if it's part of a lab or not.

**Review by brucestull — CHANGES_REQUESTED** [review]
[Todo](https://github.com/PdxCodeGuild/class_kiwi/blob/main/3%20Django/labs/02%20Todo.md)

**Needs Work**
1. "The form for creating a todo item should also have a dropdown list for selecting the priority."

Otherwise, the app works great. Complete and Un-Complete functions work well.

**Comment by efano** [comment]
For django lab3: I don't know why the priorities fields of high/med/low in the database were excluded in the push. I included them again with this followup.

**Comment by efano** [comment]
For django lab2 redo: absolute horrid re-coding, but it works and I'm tired... :)

**Review by brucestull — COMMENTED** [review]
[Grocery List](https://github.com/PdxCodeGuild/class_kiwi/blob/main/3%20Django/labs/03%20Grocery%20List)

**Completed**

Excellent execution of assignment.

**Review by brucestull — COMMENTED** [review]
[Todo](https://github.com/PdxCodeGuild/class_kiwi/blob/main/3%20Django/labs/02%20Todo.md)

**Completed**

Great CSS and execution of assignment.

**Review by brucestull — COMMENTED** [review]
[Vue Redo](https://github.com/PdxCodeGuild/class_kiwi/blob/main/4%20JavaScript/labs/03%20Vue%20Redo.md)

**Completed**

**Review by brucestull — APPROVED** [review]
**Labs completed**

**Pull request merged**
