### PR TITLE
lab5 burrito site

### PR DESCRIPTION
**Pull request by anthonybillie**
Lab 5 Submission

### CODE REVIEW

**Comment by anthonybillie** [comment]
django redo lab is in d_labs folder

**Comment by brucestull** [comment]
#170
[Lab 12 ATM](https://github.com/PdxCodeGuild/class_kiwi/blob/main/1%20Python/labs/12%20ATM.md)

1. Balance after interest accrual on $100 should be $100.10 but current version displays $110.

**Review by brucestull — COMMENTED** [review]
#170 
[Lab 14 Dad Joke](https://github.com/PdxCodeGuild/class_kiwi/blob/main/1%20Python/labs/14%20Dad%20Joke%20API.md)

- Lab satisfies MVP, marking completed.
    - If you ever want to revisit this lab, you could add handling of user input of 'yes' when the current joke is at the end of the list.

**Review by IronWill12 — APPROVED** [review]

**Review by IronWill12 — APPROVED** [review]

**Comment by brucestull** [comment]
#170
[Lab 12 ATM](https://github.com/PdxCodeGuild/class_kiwi/blob/main/1%20Python/labs/12%20ATM.md)

**Completed**
* Interest error bug fixed.

**Comment by brucestull** [comment]
[Django Redo](https://github.com/PdxCodeGuild/class_kiwi/blob/main/3%20Django/labs/01%20Django%20Redo.md)
[Lab 7: ROT Cipher](https://github.com/PdxCodeGuild/class_kiwi/blob/main/1%20Python/labs/07%20ROT13.md)

**Completed**

**Comment by brucestull** [comment]
[Lab 2: Todo](https://github.com/PdxCodeGuild/class_kiwi/blob/main/3%20Django/labs/02%20Todo.md)

**Completed**

**Comment by brucestull** [comment]
[Lab 3: Grocery List](https://github.com/PdxCodeGuild/class_kiwi/blob/main/3%20Django/labs/03%20Grocery%20List)

**Needs Work**
1. "The user should be presented with a list of incomplete items and a list of completed items. The user should be able to mark an item complete/incomplete and be able to delete an item."

**The Good Stuff**: Great feature and execution to include 'departments'.

**Comment by brucestull** [comment]
[Lab 3: Grocery List](https://github.com/PdxCodeGuild/class_kiwi/blob/main/3%20Django/labs/03%20Grocery%20List)

**Needs Work**
1. "The user should be presented with a list of incomplete items and a list of completed items. The user should be able to mark an item complete/incomplete and be able to delete an item."
    1. User should be able to change items between completed and uncompleted lists.
    2. User should be able to delete an item from either list.

**The Good Stuff**: Great feature and execution to include 'departments'.

**Pull request merged**
