### PR TITLE
HTML CSS Lab4 Burrito Order Form

### PR DESCRIPTION
**Pull request by Tatumc4561**
Lab 4 Burrito Order Form

### CODE REVIEW

**Comment by Tatumc4561** [comment]
Added Lab06 Flask, and Lab1 Django

**Comment by Tatumc4561** [comment]
Added Django Lab2 Grocery_List

**Comment by Tatumc4561** [comment]
Added lab3 Django Todo List - Styling is a bit messy but includes part 1 and 2

**Comment by Tatumc4561** [comment]
Added Lab1_JS Rock Paper Scissors Version 2

**Comment by Tatumc4561** [comment]
Added Lab2_JS Todo List

**Comment by Tatumc4561** [comment]
Updated python lab15 to show full list of authors available from API

**Review by brucestull — COMMENTED** [review]
[Lab 01: Django Redo](https://github.com/PdxCodeGuild/class_kiwi/blob/main/3%20Django/labs/01%20Django%20Redo.md)

**Completed**

**Review by brucestull — CHANGES_REQUESTED** [review]
[Lab 02: Todo](https://github.com/PdxCodeGuild/class_kiwi/blob/main/3%20Django/labs/02%20Todo.md)

**Needs Work**
1. Django project migrate fails:
    ```
    local-path\DJANGO_projects\lab3_django> python .\manage.py migrate
    ...
    ModuleNotFoundError: No module named 'todo_proj.settings'
    ...
    ```

**Comment by Tatumc4561** [comment]
> 

deleted gitignore

**Comment by Tatumc4561** [comment]
Added Lab1_vueRedo RPS

**Review by brucestull — COMMENTED** [review]
[Lab 02: Todo](https://github.com/PdxCodeGuild/class_kiwi/blob/main/3%20Django/labs/02%20Todo.md)

**Completed**

**Review by brucestull — COMMENTED** [review]
[Grocery List](https://github.com/PdxCodeGuild/class_kiwi/blob/main/3%20Django/labs/03%20Grocery%20List)

**Needs Work**
* Completed and Incompleted lists need to be separate lists.

**Comment by brucestull** [comment]
See https://github.com/PdxCodeGuild/class_kiwi/commit/bada0f15d9701adaaae418a918d7be04b5bd4673#commitcomment-74550395

**Completed**

**Review by brucestull — APPROVED** [review]

**Pull request merged**
