### PR TITLE
html lab 4 5 6

### PR DESCRIPTION
**Pull request by Omuk**
Lab 4 5 6

### CODE REVIEW

**Review by brucestull — CHANGES_REQUESTED** [review]
[Lab 3 Grocery List](https://github.com/PdxCodeGuild/class_kiwi/blob/main/3%20Django/labs/03%20Grocery%20List)

**Needs Work**
1. "The user should be presented with a list of incomplete items and a list of completed items." but is presented with a single list.

**Comment by brucestull** [comment]
[Lab 4 Blog](https://github.com/PdxCodeGuild/class_kiwi/blob/main/3%20Django/labs/04%20Blog.md)

**Completed**

**Comment by brucestull** [comment]
[Lab 3 Grocery List](https://github.com/PdxCodeGuild/class_kiwi/blob/main/3%20Django/labs/03%20Grocery%20List)

**Completed**

**Review by brucestull — COMMENTED** [review]
[Django Redo](https://github.com/PdxCodeGuild/class_kiwi/blob/main/3%20Django/labs/01%20Django%20Redo.md)

**Completed**

**Comment by Omuk** [comment]
I have just committed the vue  redo labwork.

**Review by brucestull — COMMENTED** [review]
[Lab 1: JavaScript Redo](https://github.com/PdxCodeGuild/class_kiwi/blob/main/4%20JavaScript/labs/01%20JavaScript%20Redo.md)

**Completed**

**Review by brucestull — COMMENTED** [review]
[02 JavaScript Todo List](https://github.com/PdxCodeGuild/class_kiwi/blob/main/4%20JavaScript/labs/02%20JavaScript%20Todo%20List)

**Completed**

**Review by brucestull — CHANGES_REQUESTED** [review]
[Vue Redo](https://github.com/PdxCodeGuild/class_kiwi/blob/main/4%20JavaScript/labs/03%20Vue%20Redo.md)

**Needs Work**
1. 6 feet should be about 2 meters. But app indicates about 19.7 meters.

image

**Review by IronWill12 — CHANGES_REQUESTED** [review]
Lab 06 returns 404 error.

**Pull request closed without merging**
